promtail:
  config:
    snippets:
      extraScrapeConfigs: |
        # Add an additional scrape config for syslog
        - job_name: journal
          journal:
            path: /tmp/journal
            max_age: 12h
            labels:
              job: systemd-journal
          relabel_configs:
            - source_labels:
                - '__journal__systemd_unit'
              target_label: 'unit'
            - source_labels:
                - '__journal__hostname'
              target_label: 'hostname'

  # Mount journal directory into promtail pods
  extraVolumes:
    - name: journal
      hostPath:
        path: /tmp/journal

  extraVolumeMounts:
    - name: journal
      mountPath: /tmp/journal
      readOnly: true


