server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://127.0.0.1:8081/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
# Add an additional scrape config for syslog
- job_name: journal
  journal:
    path: /var/log/journal
    max_age: 12h
    json: false
    labels:
      job: systemd-journal
  relabel_configs:
    - source_labels:
      - '__journal__systemd_unit'
      target_label: 'unit'
    - source_labels:
      - '__journal__hostname'
      target_label: 'hostname'
