## https://github.com/bitnami/charts/tree/master/bitnami/thanos/
objstoreConfig: |-
  type: s3
  config:
    bucket: metrics-a
    endpoint: 192.168.2.205:9000
    access_key: user
    secret_key: password
    insecure: true
bucketweb:
  enabled: false
compactor:      
  enabled: true
  persistence:
    enabled: false
storegateway:
  enabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
querier:
  stores:
    - prom-prometheus-operator-prometheus-thanos.metrics.svc.cluster.local:10901
receive:
  enabled: true
  logLevel: debug
  tsdbRetention: 1d