prometheus:
  enabled: true
  retention: 4h
  serviceAccount:
    create: true
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList: 
      - job_name: 'example-target-1'
        scrape_interval: 30s
        metrics_path: /
        static_configs:
        - targets: ['test-client.default:9877']
          labels:
            mylabel: "test_client"
  thanos:
    create: true
    extraArgs:
      - --log.level=debug
    objectStorageConfig:
      secretName: thanos-objstore-config
      secretKey: thanos-storage-config

