## https://github.com/bitnami/charts/tree/master/bitnami/thanos/
objstoreConfig: |-
  type: s3
  config:
    bucket: metrics-bucket-a
    endpoint: 192.168.54.99:9000
    access_key: user
    secret_key: password
    insecure: true
bucketweb:
  enabled: false
compactor:      
  enabled: true
  persistence:
    enabled: false
storegateway:
  enabled: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
querier:
  stores:
    - prom-kube-prometheus-prometheus-thanos.metrics:10901
    - dnssrv+_grpc._tcp.thanos-storegateway.metrics
receive:
  enabled: false
  logLevel: debug
  tsdbRetention: 1d
